encrypt shared key with gpg when exporting

diff --git a/ghfsync b/ghfsync
--- a/ghfsync
+++ b/ghfsync
@@ -252,27 +252,39 @@ local/
 EOC
     git add .gitignore
 }
+_add_repo() {
+    ! git remote add ${ALIAS:-origin} ${REMOTE_URL} 1>/dev/null && echo "Failed to add remote repository '${REMOTE_URL}' (${ALIAS:-origin})" && return 1
+    return 0
+}
 _init_common() {
     mkdir -p "$RHOME/$REPO"
     cd "$RHOME/$REPO"
     git init 1>/dev/null
-    ((HAS_REMOTE)) && git remote add origin ${REMOTE_URL} 1>/dev/null
+    ((HAS_REMOTE)) && _add_repo
     _create_attributes
+}
+_sync_repo() {
+    ! ((HAS_REMOTE)) && return 1
+    local x r
+    x=$(git push -u ${ALIAS:-origin} master 2>&1)
+    r=$?
+    (($r)) && echo "Failed." && echo "$x" && return 1
+    return 0
 }
 _initialise_repo() {
     _init_common
     git-crypt init 1>/dev/null
     _create_gitignore
     git commit -m"init" 1>/dev/null
-    if ((HAS_REMOTE)); then
-        local x r
-        x=$(git push -u origin master 2>&1)
-        r=$?
-        (($r)) && echo "Failed." && echo "$x" && return 1
-    fi
+    _sync_repo
     local key=$(mktemp -u kkXXXXXXX)
-    git-crypt export-key /tmp/$key 1>/dev/null || return 1
-    echo "Your private key is in /tmp/$key"
+    local pkey=/tmp/$key
+    #git-crypt export-key /tmp/$key 1>/dev/null || return 1
+    
+    echo "Please, enter a passphrase to protect your private key."
+    git-crypt export-key -- - | GPG_AGENT_INFO="" gpg --no-use-agent -o "$pkey".gpg --cipher-algo AES256 --symmetric --set-filename "$key"
+
+    echo "Your private key is in '$pkey'."
     return 0
 }
 register_repo() {
